import useThemes from '@/hooks/useThemes'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  const { setTheme, setMode } = useThemes()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={() => setTheme('blue')}>Set Blue Mode</button>
        <button onClick={() => setTheme('green')}>Set Green Mode</button>
        <br />
        <br />
        <button onClick={() => setMode('dark')}>Set Dark Mode</button>
        <button onClick={() => setMode('light')}>Set Light Mode</button>
      </main>
    </>
  )
}

export default Home
